// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Dep_b$ReactLite = require("./dep_b.bs.js");

console.log("Dep_a init...");

console.log(String(Dep_b$ReactLite.get_a(/* () */0)));

var x = "done";

exports.x = x;
/*  Not a pure module */
