// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Dep_a$ReactLite = require("./dep_a.bs.js");
var Dep_b$ReactLite = require("./dep_b.bs.js");

console.log("Main init...");

console.log(String(Dep_b$ReactLite.get_a(/* () */0)));

console.log(Dep_a$ReactLite.x);

/*  Not a pure module */
